name: Python application

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - "!**/README.md"
  pull_request:
    branches:
        - main
# on:
#   push:
#     # branches: [ master ]
#     paths:
#       - 'backend/**'
#   # pull_request:
#   #   branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./backend/app
    steps:
      - uses: actions/checkout@v2s
      - name: Set up Python 3.9
        # working-directory: ./backend
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    # - name: Run migrations
    #   run: python manage.py migrate
    # - name: Run tests
    #   run: python manage.py test
